### ISSUE TITLE
Already registerred UUID... 

### ISSUE THREAD

**Issue by nklint** [meg768/homebridge-telldus-tellstick-duo#1]
I keep getting this error.
I'm not sure what UUID it is referring to. I can mention that I previously used the tdtool based homebridge plugin.

```
/usr/local/lib/node_modules/homebridge-telldus-tellstick-duo/src/accessory.js:17
            throw new Error("Yo bro! Already registerred UUID '%s'. Must be unique.", uuid);
            ^

Error: Yo bro! Already registerred UUID '%s'. Must be unique.
    at Lightbulb.Accessory (/usr/local/lib/node_modules/homebridge-telldus-tellstick-duo/src/accessory.js:17:19)
    at Device (/usr/local/lib/node_modules/homebridge-telldus-tellstick-duo/src/device.js:14:14)
    at Switch (/usr/local/lib/node_modules/homebridge-telldus-tellstick-duo/src/switch.js:13:14)
    at Lightbulb (/usr/local/lib/node_modules/homebridge-telldus-tellstick-duo/src/lightbulb.js:4:18)
    at /usr/local/lib/node_modules/homebridge-telldus-tellstick-duo/src/platform.js:200:50
    at Array.forEach (native)
    at TelldusPlatform.createDevices (/usr/local/lib/node_modules/homebridge-telldus-tellstick-duo/src/platform.js:142:34)
    at new TelldusPlatform (/usr/local/lib/node_modules/homebridge-telldus-tellstick-duo/src/platform.js:51:14)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:294:32)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:80:36)
```

Any hints on how to resolve this?

**Comment by meg768** [comment]
It seems like you have a duplicate name in your config file under the "devices" section. The property **name** in combination with the **location** property must be a unique.

**Comment by nklint** [comment]
Hmm that can’t be the case because I tried to remove all but one devices from my config.json
I think I even tried removing all Devices. But can the duplicate UUIDs be regarding duplicates from etc/tellstick.conf?
Location property, which one is that?

**Comment by meg768** [comment]
If you specify a **devices** property in your config file, the etc/tellstick.conf is ignored and **replaced** by the devices you specify.

**Comment by meg768** [comment]
Posting your config file may help me to figure out the problem...

**Comment by meg768** [comment]
Here is an example of a motion sensor located in my office. The name/location combination must be unique.

```
...
        "devices": [{
                "name": "Motion sensor",
                "location": "Office",
                "type": "motion-sensor",
                "timeout": "30",

                "notify": {
                    "on": "Movement in the office"
                },

                "protocol": "arctech",
                "model": "selflearning-switch",

                "parameters": {
                    "house": "15452146",
                    "unit": "16",
                    "group": "0"
                }
            },
...

```

**Comment by nklint** [comment]
Okey, thats intresting I didn't a single example in the instructions with a location.
I think my config is according to the instructions provided.
```
...
{
  "platform": "Telldus Tellstick Duo",
  "name": "Telldus Tellstick Duo",
  "sensors": [
    {
      "id": 183,
      "name": "Uterummet"
    }
  ],
  "devices": [
    {
      "name": "Glaskuber",
      "type": "lightbulb",
      "protocol": "arctech",
      "model": "codeswitch",
      "parameters": {
        "group": "0",
        "unit": "3",
        "house": "A"
      }
    },
    {
      "name": "Mysbelysning",
      "type": "lightbulb",
      "protocol": "arctech",
      "model": "codeswitch",
      "parameters": {
        "group": "0",
        "unit": "2",
        "house": "A"
      }
    }
  ]
}
...
```

I will try to modify my config according to your provided sample and see if it makes a differance.

**Comment by nklint** [comment]
Now I tried re-installing the plugin but now I get this issue instead, when starting the homebride service:
```
[2018-03-26 19:07:37] Loading 1 platforms...
[2018-03-26 19:07:37] [Telldus Tellstick Duo] Initializing Telldus Tellstick Duo platform...
/usr/local/lib/node_modules/homebridge-telldus-tellstick-duo/src/platform.js:219
                device.initialize();
                      ^

TypeError: Cannot read property 'initialize' of undefined
    at /usr/local/lib/node_modules/homebridge-telldus-tellstick-duo/src/platform.js:219:23
    at Array.forEach (native)
    at TelldusPlatform.createDevices (/usr/local/lib/node_modules/homebridge-telldus-tellstick-duo/src/platform.js:142:34)
    at new TelldusPlatform (/usr/local/lib/node_modules/homebridge-telldus-tellstick-duo/src/platform.js:51:14)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:294:32)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:80:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:40:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
```

**Comment by meg768** [comment]
Jo, gjorde någon ändring där för ett tag sedan. Github och npm var inte riktigt i synk. Prova nu.  
Lade ut en ny version av npm-modulen..

**Comment by nklint** [comment]
Okey, we are definetly making progress =)
I Got it working now, unfotunately not with all my accessories though..
Now i get this error.
```
[2018-03-26 23:46:31] Loaded config.json with 0 accessories and 1 platforms.
[2018-03-26 23:46:31] ---
[2018-03-26 23:46:31] Loading 1 platforms...
[2018-03-26 23:46:31] [Telldus Tellstick Duo] Initializing Telldus Tellstick Duo platform...
[2018-03-26 23:46:32] [Telldus Tellstick Duo] Initializing platform accessory 'Fasad - Ute'...
[2018-03-26 23:46:32] [Telldus Tellstick Duo] Initializing platform accessory 'Terassen - Ute'...
[2018-03-26 23:46:32] [Telldus Tellstick Duo] Initializing platform accessory 'Glaskuber - Vardagsrummet'...
[2018-03-26 23:46:32] [Telldus Tellstick Duo] Initializing platform accessory 'Mysbelysning - Hemma'...
/usr/local/lib/node_modules/homebridge/lib/server.js:360
          var accessoryName = accessoryInstance.name; // assume this property was set
                                               ^

TypeError: Cannot read property 'name' of undefined
```
I have tried to move around the declarations of my devices and this makes the error occur at different locations. I tried moving the failing device last in the list. in order to make moore devices be discovered. But then the error occurred at the same position.

Can you recognize this error and can you spot the problem with my config (below)

```
{
  "bridge": {
    "name": "Bridge Telldus",
    "username": "CC:22:3D:E3:CE:32",
    "port": 51826,
    "pin": "123-45-678"
  },
  "description": "Bridging Tellstick duo",
  "platforms": [
    {
      "platform": "Telldus Tellstick Duo",
      "name": "Telldus Tellstick Duo",
      "sensors": [
        {
          "name": "termometer",
          "location": "Uterum",
          "id": 183
        }
      ],
      "devices": [
        {
          "name": "Fasad",
          "location": "Ute",
          "type": "lightbulb",
          "protocol": "arctech",
          "model": "selflearning-switch",
          "parameters": {
            "group": "0",
            "unit": "2",
            "house": "3629"
          }
        },
        {
          "name": "Terassen",
          "location": "Ute",
          "type": "lightbulb",
          "protocol": "arctech",
          "model": "selflearning-switch",
          "parameters": {
            "group": "0",
            "unit": "2",
            "house": "15294714"
          }
        },
        {
          "name": "Glaskuber",
          "location": "Vardagsrummet",
          "type": "lightbulb",
          "protocol": "arctech",
          "model": "codeswitch",
          "parameters": {
            "group": "0",
            "unit": "3",
            "house": "A"
          }
        },
        {
          "name": "Mysbelysning",
          "location": "Hemma",
          "type": "lightbulb",
          "protocol": "arctech",
          "model": "codeswitch",
          "parameters": {
            "group": "0",
            "unit": "2",
            "house": "A"
          }
        },
        {
          "name": "Slinga i uterum",
          "location": "Uterum",
          "type": "lightbulb",
          "protocol": "arctech",
          "model": "selflearning-dimmer",
          "parameters": {
            "group": "0",
            "unit": "1",
            "house": "29523"
          }
        },
        {
          "name": "Deathstar",
          "location": "Uterum",
          "type": "lightbulb",
          "protocol": "arctech",
          "model": "selflearning-switch",
          "parameters": {
            "group": "0",
            "unit": "2",
            "house": "8436555"
          }
        }
      ]
    }
  ]
}
```

Thanks a lot for your support!

**Comment by nklint** [comment]
I Found the issue!
**"model": "selflearning-dimmer"**
```
{
          "name": "Slinga i uterum",
          "location": "Uterum",
          "type": "lightbulb",
          "protocol": "arctech",
          "model": "selflearning-dimmer",
          "parameters": {
            "group": "0",
            "unit": "1",
            "house": "29523"
          }
        }
```
